---
name: Text-Diff-HTML
version: 0.05
author:
  - 'David Wheeler <david@kineticode.com>'
abstract: XHTML format for Text::Diff::Unified
license: perl
resources:
  license: http://dev.perl.org/licenses/
configure_requires:
  Module::Build: 0.2701
requires:
  HTML::Entities: 0
  Text::Diff: 0.11
build_requires:
  Module::Build: 0.2701
  Test::More: 0.17
recommends:
  Test::Pod: 1.20
provides:
  Text::Diff::HTML:
    file: lib/Text/Diff/HTML.pm
    version: 0.05
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
